version: "3.9"

networks:
  bridge-network:
    driver: bridge

volumes:
  db:
  bundle_cache:

services:
  db:
    image: postgres:14.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - bridge-network

  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./.dockerdev/Dockerfile
    working_dir: /app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      BUNDLE_PATH: /bundle/vendor
      RAILS_ENV: development
      PORT: 3000
    command: /bin/sh ".dockerdev/commander/commander.dev.sh"
    volumes:
      - .:/app:rw
      - bundle_cache:/bundle/vendor
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - bridge-network
